// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.32.0--rc1
// source: internal/otpauthpb/migration.proto

package otpauthpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Algorithm int32

const (
	Algorithm_ALGORITHM_UNSPECIFIED Algorithm = 0
	Algorithm_ALGORITHM_SHA1        Algorithm = 1
	Algorithm_ALGORITHM_SHA256      Algorithm = 2
	Algorithm_ALGORITHM_SHA512      Algorithm = 3
	Algorithm_ALGORITHM_MD5         Algorithm = 4
)

// Enum value maps for Algorithm.
var (
	Algorithm_name = map[int32]string{
		0: "ALGORITHM_UNSPECIFIED",
		1: "ALGORITHM_SHA1",
		2: "ALGORITHM_SHA256",
		3: "ALGORITHM_SHA512",
		4: "ALGORITHM_MD5",
	}
	Algorithm_value = map[string]int32{
		"ALGORITHM_UNSPECIFIED": 0,
		"ALGORITHM_SHA1":        1,
		"ALGORITHM_SHA256":      2,
		"ALGORITHM_SHA512":      3,
		"ALGORITHM_MD5":         4,
	}
)

func (x Algorithm) Enum() *Algorithm {
	p := new(Algorithm)
	*p = x
	return p
}

func (x Algorithm) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Algorithm) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_otpauthpb_migration_proto_enumTypes[0].Descriptor()
}

func (Algorithm) Type() protoreflect.EnumType {
	return &file_internal_otpauthpb_migration_proto_enumTypes[0]
}

func (x Algorithm) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Algorithm.Descriptor instead.
func (Algorithm) EnumDescriptor() ([]byte, []int) {
	return file_internal_otpauthpb_migration_proto_rawDescGZIP(), []int{0}
}

type DigitCount int32

const (
	DigitCount_DIGIT_COUNT_UNSPECIFIED DigitCount = 0
	DigitCount_DIGIT_COUNT_SIX         DigitCount = 1
	DigitCount_DIGIT_COUNT_EIGHT       DigitCount = 2
)

// Enum value maps for DigitCount.
var (
	DigitCount_name = map[int32]string{
		0: "DIGIT_COUNT_UNSPECIFIED",
		1: "DIGIT_COUNT_SIX",
		2: "DIGIT_COUNT_EIGHT",
	}
	DigitCount_value = map[string]int32{
		"DIGIT_COUNT_UNSPECIFIED": 0,
		"DIGIT_COUNT_SIX":         1,
		"DIGIT_COUNT_EIGHT":       2,
	}
)

func (x DigitCount) Enum() *DigitCount {
	p := new(DigitCount)
	*p = x
	return p
}

func (x DigitCount) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DigitCount) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_otpauthpb_migration_proto_enumTypes[1].Descriptor()
}

func (DigitCount) Type() protoreflect.EnumType {
	return &file_internal_otpauthpb_migration_proto_enumTypes[1]
}

func (x DigitCount) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DigitCount.Descriptor instead.
func (DigitCount) EnumDescriptor() ([]byte, []int) {
	return file_internal_otpauthpb_migration_proto_rawDescGZIP(), []int{1}
}

type OTPType int32

const (
	OTPType_OTP_TYPE_UNSPECIFIED OTPType = 0
	OTPType_OTP_TYPE_HOTP        OTPType = 1
	OTPType_OTP_TYPE_TOTP        OTPType = 2
)

// Enum value maps for OTPType.
var (
	OTPType_name = map[int32]string{
		0: "OTP_TYPE_UNSPECIFIED",
		1: "OTP_TYPE_HOTP",
		2: "OTP_TYPE_TOTP",
	}
	OTPType_value = map[string]int32{
		"OTP_TYPE_UNSPECIFIED": 0,
		"OTP_TYPE_HOTP":        1,
		"OTP_TYPE_TOTP":        2,
	}
)

func (x OTPType) Enum() *OTPType {
	p := new(OTPType)
	*p = x
	return p
}

func (x OTPType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OTPType) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_otpauthpb_migration_proto_enumTypes[2].Descriptor()
}

func (OTPType) Type() protoreflect.EnumType {
	return &file_internal_otpauthpb_migration_proto_enumTypes[2]
}

func (x OTPType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OTPType.Descriptor instead.
func (OTPType) EnumDescriptor() ([]byte, []int) {
	return file_internal_otpauthpb_migration_proto_rawDescGZIP(), []int{2}
}

type MigrationPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OtpParameters []*OTPParameters       `protobuf:"bytes,1,rep,name=otp_parameters,json=otpParameters,proto3" json:"otp_parameters,omitempty"`
	Version       int32                  `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	BatchSize     int32                  `protobuf:"varint,3,opt,name=batch_size,json=batchSize,proto3" json:"batch_size,omitempty"`
	BatchIndex    int32                  `protobuf:"varint,4,opt,name=batch_index,json=batchIndex,proto3" json:"batch_index,omitempty"`
	BatchId       int32                  `protobuf:"varint,5,opt,name=batch_id,json=batchId,proto3" json:"batch_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MigrationPayload) Reset() {
	*x = MigrationPayload{}
	mi := &file_internal_otpauthpb_migration_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MigrationPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MigrationPayload) ProtoMessage() {}

func (x *MigrationPayload) ProtoReflect() protoreflect.Message {
	mi := &file_internal_otpauthpb_migration_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MigrationPayload.ProtoReflect.Descriptor instead.
func (*MigrationPayload) Descriptor() ([]byte, []int) {
	return file_internal_otpauthpb_migration_proto_rawDescGZIP(), []int{0}
}

func (x *MigrationPayload) GetOtpParameters() []*OTPParameters {
	if x != nil {
		return x.OtpParameters
	}
	return nil
}

func (x *MigrationPayload) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *MigrationPayload) GetBatchSize() int32 {
	if x != nil {
		return x.BatchSize
	}
	return 0
}

func (x *MigrationPayload) GetBatchIndex() int32 {
	if x != nil {
		return x.BatchIndex
	}
	return 0
}

func (x *MigrationPayload) GetBatchId() int32 {
	if x != nil {
		return x.BatchId
	}
	return 0
}

type OTPParameters struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Secret        []byte                 `protobuf:"bytes,1,opt,name=secret,proto3" json:"secret,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Issuer        string                 `protobuf:"bytes,3,opt,name=issuer,proto3" json:"issuer,omitempty"`
	Algorithm     Algorithm              `protobuf:"varint,4,opt,name=algorithm,proto3,enum=otpauthpb.Algorithm" json:"algorithm,omitempty"`
	Digits        DigitCount             `protobuf:"varint,5,opt,name=digits,proto3,enum=otpauthpb.DigitCount" json:"digits,omitempty"`
	Type          OTPType                `protobuf:"varint,6,opt,name=type,proto3,enum=otpauthpb.OTPType" json:"type,omitempty"`
	Counter       int64                  `protobuf:"varint,7,opt,name=counter,proto3" json:"counter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OTPParameters) Reset() {
	*x = OTPParameters{}
	mi := &file_internal_otpauthpb_migration_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OTPParameters) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OTPParameters) ProtoMessage() {}

func (x *OTPParameters) ProtoReflect() protoreflect.Message {
	mi := &file_internal_otpauthpb_migration_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OTPParameters.ProtoReflect.Descriptor instead.
func (*OTPParameters) Descriptor() ([]byte, []int) {
	return file_internal_otpauthpb_migration_proto_rawDescGZIP(), []int{1}
}

func (x *OTPParameters) GetSecret() []byte {
	if x != nil {
		return x.Secret
	}
	return nil
}

func (x *OTPParameters) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *OTPParameters) GetIssuer() string {
	if x != nil {
		return x.Issuer
	}
	return ""
}

func (x *OTPParameters) GetAlgorithm() Algorithm {
	if x != nil {
		return x.Algorithm
	}
	return Algorithm_ALGORITHM_UNSPECIFIED
}

func (x *OTPParameters) GetDigits() DigitCount {
	if x != nil {
		return x.Digits
	}
	return DigitCount_DIGIT_COUNT_UNSPECIFIED
}

func (x *OTPParameters) GetType() OTPType {
	if x != nil {
		return x.Type
	}
	return OTPType_OTP_TYPE_UNSPECIFIED
}

func (x *OTPParameters) GetCounter() int64 {
	if x != nil {
		return x.Counter
	}
	return 0
}

var File_internal_otpauthpb_migration_proto protoreflect.FileDescriptor

const file_internal_otpauthpb_migration_proto_rawDesc = "" +
	"\n" +
	"\"internal/otpauthpb/migration.proto\x12\totpauthpb\"\xc8\x01\n" +
	"\x10MigrationPayload\x12?\n" +
	"\x0eotp_parameters\x18\x01 \x03(\v2\x18.otpauthpb.OTPParametersR\rotpParameters\x12\x18\n" +
	"\aversion\x18\x02 \x01(\x05R\aversion\x12\x1d\n" +
	"\n" +
	"batch_size\x18\x03 \x01(\x05R\tbatchSize\x12\x1f\n" +
	"\vbatch_index\x18\x04 \x01(\x05R\n" +
	"batchIndex\x12\x19\n" +
	"\bbatch_id\x18\x05 \x01(\x05R\abatchId\"\xf8\x01\n" +
	"\rOTPParameters\x12\x16\n" +
	"\x06secret\x18\x01 \x01(\fR\x06secret\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06issuer\x18\x03 \x01(\tR\x06issuer\x122\n" +
	"\talgorithm\x18\x04 \x01(\x0e2\x14.otpauthpb.AlgorithmR\talgorithm\x12-\n" +
	"\x06digits\x18\x05 \x01(\x0e2\x15.otpauthpb.DigitCountR\x06digits\x12&\n" +
	"\x04type\x18\x06 \x01(\x0e2\x12.otpauthpb.OTPTypeR\x04type\x12\x18\n" +
	"\acounter\x18\a \x01(\x03R\acounter*y\n" +
	"\tAlgorithm\x12\x19\n" +
	"\x15ALGORITHM_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eALGORITHM_SHA1\x10\x01\x12\x14\n" +
	"\x10ALGORITHM_SHA256\x10\x02\x12\x14\n" +
	"\x10ALGORITHM_SHA512\x10\x03\x12\x11\n" +
	"\rALGORITHM_MD5\x10\x04*U\n" +
	"\n" +
	"DigitCount\x12\x1b\n" +
	"\x17DIGIT_COUNT_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fDIGIT_COUNT_SIX\x10\x01\x12\x15\n" +
	"\x11DIGIT_COUNT_EIGHT\x10\x02*I\n" +
	"\aOTPType\x12\x18\n" +
	"\x14OTP_TYPE_UNSPECIFIED\x10\x00\x12\x11\n" +
	"\rOTP_TYPE_HOTP\x10\x01\x12\x11\n" +
	"\rOTP_TYPE_TOTP\x10\x02B\x15Z\x13/internal/otpauthpbb\x06proto3"

var (
	file_internal_otpauthpb_migration_proto_rawDescOnce sync.Once
	file_internal_otpauthpb_migration_proto_rawDescData []byte
)

func file_internal_otpauthpb_migration_proto_rawDescGZIP() []byte {
	file_internal_otpauthpb_migration_proto_rawDescOnce.Do(func() {
		file_internal_otpauthpb_migration_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_otpauthpb_migration_proto_rawDesc), len(file_internal_otpauthpb_migration_proto_rawDesc)))
	})
	return file_internal_otpauthpb_migration_proto_rawDescData
}

var file_internal_otpauthpb_migration_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_internal_otpauthpb_migration_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_internal_otpauthpb_migration_proto_goTypes = []any{
	(Algorithm)(0),           // 0: otpauthpb.Algorithm
	(DigitCount)(0),          // 1: otpauthpb.DigitCount
	(OTPType)(0),             // 2: otpauthpb.OTPType
	(*MigrationPayload)(nil), // 3: otpauthpb.MigrationPayload
	(*OTPParameters)(nil),    // 4: otpauthpb.OTPParameters
}
var file_internal_otpauthpb_migration_proto_depIdxs = []int32{
	4, // 0: otpauthpb.MigrationPayload.otp_parameters:type_name -> otpauthpb.OTPParameters
	0, // 1: otpauthpb.OTPParameters.algorithm:type_name -> otpauthpb.Algorithm
	1, // 2: otpauthpb.OTPParameters.digits:type_name -> otpauthpb.DigitCount
	2, // 3: otpauthpb.OTPParameters.type:type_name -> otpauthpb.OTPType
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_internal_otpauthpb_migration_proto_init() }
func file_internal_otpauthpb_migration_proto_init() {
	if File_internal_otpauthpb_migration_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_otpauthpb_migration_proto_rawDesc), len(file_internal_otpauthpb_migration_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_otpauthpb_migration_proto_goTypes,
		DependencyIndexes: file_internal_otpauthpb_migration_proto_depIdxs,
		EnumInfos:         file_internal_otpauthpb_migration_proto_enumTypes,
		MessageInfos:      file_internal_otpauthpb_migration_proto_msgTypes,
	}.Build()
	File_internal_otpauthpb_migration_proto = out.File
	file_internal_otpauthpb_migration_proto_goTypes = nil
	file_internal_otpauthpb_migration_proto_depIdxs = nil
}
